baseURL : 'https://diegoroccia.github.io/'
languageCode : 'en-us'
title : 'My New Hugo Site'
theme : "PaperMod"
socialIcons:
    - name: "kofi"
      url: "https://kofi.com"
    - name: "twitter"
      url: "https://twitter.com"
